# Generated by Django 5.2.3 on 2025-06-30 19:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FingerprintData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('lastFingerId', models.IntegerField(default=0)),
                ('startTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('scanInterval', models.IntegerField(default=100)),
            ],
            options={
                'verbose_name': 'Fingerprint Data',
                'verbose_name_plural': 'Fingerprint Data',
                'db_table': 'fingerprint_data',
            },
        ),
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=50)),
                ('student_roll', models.CharField(max_length=20, unique=True)),
                ('student_reg', models.CharField(max_length=10, unique=True)),
                ('student_session', models.CharField(max_length=20)),
                ('student_email', models.EmailField(max_length=50, unique=True)),
                ('student_phone', models.CharField(max_length=15, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('finger_id', models.IntegerField(blank=True, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Student Info',
                'verbose_name_plural': 'Student Infos',
                'db_table': 'student_info',
            },
        ),
        migrations.CreateModel(
            name='TempRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('roll', models.CharField(max_length=20, unique=True)),
                ('reg', models.CharField(max_length=10, unique=True)),
                ('session', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('verification_token', models.CharField(blank=True, max_length=100, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Temporary Registration',
                'verbose_name_plural': 'Temporary Registrations',
                'db_table': 'temp_registration',
            },
        ),
    ]
